<a href="https://colab.research.google.com/github/lkjh1121/Colab/blob/master/Ch01.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2022/04/25
이름 : 김재현 
내용 : 파이썬 Numpy 패키지 실습

Numpy 라이브러리
 - 고성능 수치계산을 위한 파이썬 라이브러리
 - 파이썬 기본 리스트 보다 더 크고 빠른 연산을 위한 리스트를 제공
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np

In [8]:
# 벡터(Numpy 자료구조)
v1 = np.array([1, 2, 3, 4, 5])
print(v1)

v2 = np.arange(10)
print(v2)

v3 = np.arange(100)
print(v3)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
#0 ~ 1 사이의 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.54354969, 0.06411544, 0.94248618, 0.56897844, 0.22402034,
       0.93297205, 0.1019327 , 0.53891157, 0.22457225, 0.58156432,
       0.46136206, 0.54229793, 0.68429737, 0.44898097, 0.2004986 ,
       0.63424909, 0.28907284, 0.25417348, 0.71700491, 0.98418144,
       0.56665689, 0.01094838, 0.29003379, 0.78286671, 0.71785247,
       0.59528583, 0.75441525, 0.21011254, 0.02060848, 0.54008655,
       0.07972528, 0.61437105, 0.25209226, 0.96299087, 0.04471575,
       0.25885006, 0.14104161, 0.42874504, 0.18922586, 0.43722453,
       0.86121272, 0.56279281, 0.31592664, 0.04592601, 0.66162122,
       0.19573084, 0.2299245 , 0.43652426, 0.66216734, 0.76247253,
       0.90760116, 0.82536104, 0.85927515, 0.62524124, 0.28340237,
       0.51099173, 0.63983757, 0.41730862, 0.98376799, 0.19391387,
       0.84672775, 0.31802612, 0.74675547, 0.33450586, 0.00553926,
       0.54894773, 0.57319247, 0.47775256, 0.71409894, 0.36865939,
       0.57976296, 0.23930104, 0.41421897, 0.52527219, 0.08303

In [12]:
# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-1.98964677e-02,  5.08755532e-01,  9.52444660e-02, -6.75671946e-01,
       -2.48626184e-01, -5.43899023e-01, -5.92981344e-01,  5.66154427e-01,
       -8.92018882e-01, -6.68271572e-02,  1.00587231e+00,  1.07257874e-01,
       -8.57254530e-01,  5.56062564e-01, -3.74422205e-02, -1.25665966e+00,
        4.60487326e-02,  8.84667234e-01,  1.06391255e-04,  7.11599061e-01,
       -4.76054329e-02,  5.90711357e-01,  2.07872163e+00,  1.85229610e+00,
        2.69808121e-01, -7.06966865e-01, -5.56143073e-02,  4.49318955e-01,
        1.15772464e+00,  1.35767965e-01,  8.91340365e-01, -1.06776306e-01,
       -1.59529682e+00,  1.69322079e+00,  1.90016536e-01,  2.26325025e-01,
       -2.66904149e-02,  1.03186283e+00,  2.13494109e+00, -1.31902962e+00,
       -3.19316038e-01,  1.75234599e-01,  2.48624389e+00,  2.12123924e-01,
        1.36224397e+00,  2.55290322e+00,  1.32444209e+00,  5.90376705e-01,
       -1.33051585e+00, -1.04620036e+00, -1.78580277e+00,  1.39988942e-01,
       -6.96763097e-01,  

In [18]:
# 행렬 (Numpy 자료구조)
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.zeros([2, 3])
print(m3)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# 단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# 역행렬
im1 = np.linalg.inv(m1)
print(im1)

result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [31]:
#행렬 인덱싱
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print('r1 :', mat[0, 0])
print('r2 :', mat[0, :])
print('r3 :', mat[:, 0])

print('r4 :', mat[0:2, 0:2])
print('r5 :', mat[:, 0:2])
print('r6 :', mat[:, 2:4])
print('r7 :', mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
r1 : 1
r2 : [1 2 3 4]
r3 : [1 5 9]
r4 : [[1 2]
 [5 6]]
r5 : [[ 1  2]
 [ 5  6]
 [ 9 10]]
r6 : [[ 3  4]
 [ 7  8]
 [11 12]]
r7 : [[ 6  7]
 [10 11]]
